# Generated by Django 4.2.27 on 2025-12-18 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatconversation',
            name='kibana_conversation_id',
            field=models.CharField(blank=True, help_text='Kibana Agent Builder conversation ID (set after first API call)', max_length=255, null=True),
        ),
    ]
