# Generated by Django 4.2.26 on 2026-01-15 06:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_add_kibana_conversation_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Artifact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(help_text="Unique identifier within the conversation (e.g., 'main-component')", max_length=100)),
                ('title', models.CharField(help_text='Human-readable title for the artifact', max_length=200)),
                ('artifact_type', models.CharField(choices=[('code', 'Code'), ('markdown', 'Markdown Document'), ('html', 'HTML'), ('svg', 'SVG Image'), ('mermaid', 'Mermaid Diagram'), ('json', 'JSON Data'), ('csv', 'CSV Data'), ('text', 'Plain Text')], default='code', max_length=20)),
                ('language', models.CharField(blank=True, help_text="Programming language for code artifacts (e.g., 'python', 'javascript')", max_length=50)),
                ('content', models.TextField(help_text='The artifact content')),
                ('share_token', models.CharField(blank=True, help_text='Token for public sharing (if shared)', max_length=64, null=True, unique=True)),
                ('is_public', models.BooleanField(default=False, help_text='Whether this artifact is publicly accessible via share link')),
                ('version', models.PositiveIntegerField(default=1, help_text='Version number (incremented on updates)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artifacts', to='chat.chatconversation')),
                ('message', models.ForeignKey(blank=True, help_text='The message that generated this artifact', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='artifacts', to='chat.chatmessage')),
            ],
            options={
                'verbose_name': 'Artifact',
                'verbose_name_plural': 'Artifacts',
                'ordering': ['-created_at'],
                'unique_together': {('conversation', 'identifier', 'version')},
            },
        ),
    ]
