# Generated by Django 4.2.26 on 2026-01-15 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_add_artifact_model'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatconversation',
            name='kibana_conversation_id',
        ),
    ]
