# Generated by Django 4.2.27 on 2026-01-30 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_remove_kibana_conversation_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='artifact',
            name='chart_config',
            field=models.JSONField(blank=True, help_text='Chart.js configuration for dashboard artifacts', null=True),
        ),
        migrations.AlterField(
            model_name='artifact',
            name='artifact_type',
            field=models.CharField(choices=[('code', 'Code'), ('markdown', 'Markdown Document'), ('html', 'HTML'), ('svg', 'SVG Image'), ('mermaid', 'Mermaid Diagram'), ('json', 'JSON Data'), ('csv', 'CSV Data'), ('text', 'Plain Text'), ('dashboard', 'Dashboard')], default='code', max_length=20),
        ),
    ]
