"""
Django settings for CodePathfinder project.

Generated by 'django-admin startproject' using Django 4.2.26.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
import os
import dj_database_url

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# Environment detection
ENV = os.getenv('DJANGO_ENV', 'development')  # 'production' or 'development'
IS_PRODUCTION = ENV == 'production'

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('DJANGO_SECRET_KEY', 'django-insecure-z7w$&hn2iu4pq94#-%53h&8++ybw)#7$1r0b6*0s5-uzx@_l5z')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = not IS_PRODUCTION

if IS_PRODUCTION:
    ALLOWED_HOSTS = ['*']
else:
    ALLOWED_HOSTS = ['grabowskit.tplinkdns.com', 'www.codepathfinder.com', 'codepathfinder.com', 'localhost', '127.0.0.1', 'web', 'testserver', '.ngrok-free.app', '.ngrok-free.dev', '.ngrok.io']



# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',  # Required by allauth
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.google',
    'rest_framework',  # Django REST Framework
    'drf_spectacular',  # OpenAPI documentation
    'core',
    'projects',
    'api',  # REST API endpoints
    'oauth2_provider',
    'mcp_server',
    'chat',  # LibreChat integration
    'skills',  # AI agent skills system
    'django.contrib.humanize',
]

MIDDLEWARE = [
    'mcp_server.middleware.RequestDebugMiddleware',  # Debug MCP requests
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',  # Serve static files in production
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    "allauth.account.middleware.AccountMiddleware",
    'core.middleware.RequestLoggingMiddleware',
]

ROOT_URLCONF = 'CodePathfinder.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'django.template.context_processors.csrf',
            ],
        },
    },
]

WSGI_APPLICATION = 'CodePathfinder.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

# Use Postgres for both production and development
if os.getenv('DATABASE_URL'):
    DATABASES = {
        'default': dj_database_url.config(
            default=os.getenv('DATABASE_URL'),
            conn_max_age=600,
            conn_health_checks=True,
        )
    }
else:
    # Fail fast if database is not configured - ensuring we don't accidentally use local SQLite
    raise ValueError("DATABASE_URL must be set in the environment.")



# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
    {
        'NAME': 'core.validators.ComplexPasswordValidator',
    },
]



# Security Settings
SECURE_SSL_REDIRECT = False
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
SESSION_COOKIE_SECURE = True
CSRF_COOKIE_SECURE = True
SESSION_COOKIE_NAME = 'cpf_sessionid'
CSRF_COOKIE_NAME = 'cpf_csrftoken'
CSRF_COOKIE_SAMESITE = 'Lax'
USE_X_FORWARDED_HOST = True
USE_X_FORWARDED_PORT = True

# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'  # For collectstatic

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

AUTH_USER_MODEL = 'core.User'

LOGIN_URL = 'account_login'
LOGIN_REDIRECT_URL = 'project_list'
LOGOUT_REDIRECT_URL = 'home'

STATICFILES_DIRS = [
    BASE_DIR / 'static',
]

# WhiteNoise configuration for production static files
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# Email Configuration
EMAIL_BACKEND = os.getenv('EMAIL_BACKEND', 'django.core.mail.backends.console.EmailBackend')
EMAIL_HOST = os.getenv('EMAIL_HOST', 'smtp.gmail.com')
EMAIL_PORT = int(os.getenv('EMAIL_PORT', '587'))
EMAIL_USE_TLS = os.getenv('EMAIL_USE_TLS', 'True').lower() == 'true'
EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER', '')
EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD', '')
DEFAULT_FROM_EMAIL = os.getenv('DEFAULT_FROM_EMAIL', 'noreply@codepathfinder.com')

AUTHENTICATION_BACKENDS = [
    'core.backends.EmailOrUsernameModelBackend',
    'django.contrib.auth.backends.ModelBackend',
    'allauth.account.auth_backends.AuthenticationBackend',
    'oauth2_provider.backends.OAuth2Backend',
]

# Django Allauth Configuration
SITE_ID = 1

SOCIALACCOUNT_PROVIDERS = {
    'google': {
        'SCOPE': [
            'profile',
            'email',
        ],
        'AUTH_PARAMS': {
            'access_type': 'online',
        }
    }
}

# Django Allauth settings (updated to new format)
ACCOUNT_LOGIN_METHODS = {'username', 'email'}
ACCOUNT_SIGNUP_FIELDS = ['email*', 'username*', 'password1*', 'password2*']
ACCOUNT_EMAIL_VERIFICATION = 'none'
SOCIALACCOUNT_LOGIN_ON_GET = True
SOCIALACCOUNT_AUTO_SIGNUP = True

# CSRF Settings
CSRF_TRUSTED_ORIGINS = [
    'http://localhost:8000',
    'http://127.0.0.1:8000',
    'https://code-pathfinder.fly.dev',
    'https://codepathfinder.com',
    'https://www.codepathfinder.com',
    'https://localhost:8443',
    'https://127.0.0.1:8443',
]
if IS_PRODUCTION:
    pass # These are now in the base list
else:
    CSRF_TRUSTED_ORIGINS.extend(['http://grabowskit.tplinkdns.com', 'https://*.ngrok-free.app', 'https://*.ngrok-free.dev', 'https://*.ngrok.io'])

ACCOUNT_ADAPTER = 'core.adapters.AccountAdapter'
SOCIALACCOUNT_ADAPTER = 'core.adapters.SocialAccountAdapter'

# Trust X-Forwarded-Proto header from GKE Ingress (must be set before other security settings)
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

# Production security settings
if IS_PRODUCTION:
    SECURE_SSL_REDIRECT = False # Let Ingress handle SSL redirection to avoid health check failures
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_BROWSER_XSS_FILTER = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
    X_FRAME_OPTIONS = 'DENY'  # LibreChat is now a redirect, not an iframe
    SECURE_HSTS_SECONDS = 31536000
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
    # Cross-subdomain session cookie so Django session is sent when LibreChat iframe redirects to /o/authorize/
    SESSION_COOKIE_DOMAIN = '.codepathfinder.com'
    SESSION_COOKIE_SAMESITE = 'None'

OAUTH2_PROVIDER = {
    # OIDC support — CodePathfinder acts as identity provider for LibreChat
    'OIDC_ENABLED': True,
    'OIDC_RSA_PRIVATE_KEY': os.environ.get('OIDC_RSA_PRIVATE_KEY'),
    'OAUTH2_VALIDATOR_CLASS': 'core.oauth_validators.CustomOIDCValidator',
    # RP-Initiated Logout — enables /o/logout/ and advertises end_session_endpoint
    'OIDC_RP_INITIATED_LOGOUT_ENABLED': True,
    'OIDC_RP_INITIATED_LOGOUT_ALWAYS_PROMPT': False,
    'OIDC_RP_INITIATED_LOGOUT_ACCEPT_EXPIRED_TOKENS': True,
    'OIDC_RP_INITIATED_LOGOUT_DELETE_TOKENS': True,
    # Available scopes (openid/profile/email required for OIDC)
    'SCOPES': {
        'read': 'Read scope',
        'write': 'Write scope',
        'groups': 'Access to your groups',
        'mcp': 'Access MCP Server',
        'openid': 'OpenID Connect scope',
        'profile': 'User profile',
        'email': 'User email',
    },
    # PKCE is required for public clients (OAuth 2.1)
    'PKCE_REQUIRED': False,  # Allow both PKCE and non-PKCE flows for compatibility
    # Allow all redirect URI schemes for MCP clients
    'ALLOWED_REDIRECT_URI_SCHEMES': ['http', 'https', 'cursor'],
    'OIDC_RESPONSE_TYPES_SUPPORTED': ['code'],
    # Pin the public-facing issuer URL so the discovery doc always emits the right base URL
    # regardless of which internal hostname fetched it (e.g. LibreChat on the Docker network).
    'OIDC_ISS_ENDPOINT': os.environ.get('OIDC_ISS_ENDPOINT', ''),
}

OAUTH2_PROVIDER_APPLICATION_MODEL = 'oauth2_provider.Application'

LOGIN_URL = '/accounts/login/'

# Logging Configuration
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {process:d} {thread:d} {message}',
            'style': '{',
        },
        'simple': {
            'format': '{levelname} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'level': 'INFO',
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
        },
    },
    'root': {
        'handlers': ['console'],
        'level': 'INFO',
    },
    'loggers': {
        'django': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': True,
        },
        'django.request': {
            'handlers': ['console'],
            'level': 'WARNING',
            'propagate': True,
        },
        'mcp_server': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': True,
        },
    },
}

# Django REST Framework Configuration
REST_FRAMEWORK = {
    # Authentication classes
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.SessionAuthentication',  # For browsable API
        'projects.authentication.ProjectAPIKeyAuthentication',  # Project API keys (Phase 3)
    ],

    # Permission classes
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],

    # Throttling (rate limiting)
    'DEFAULT_THROTTLE_CLASSES': [
        'rest_framework.throttling.AnonRateThrottle',
        'rest_framework.throttling.UserRateThrottle',
    ],
    'DEFAULT_THROTTLE_RATES': {
        'anon': '100/hour',  # Anonymous users
        'user': '1000/hour',  # Authenticated users
        'project_api_key': '60/minute',  # Project API keys
        'chat': '30/minute',  # Chat messages (more generous for conversational flow)
        # Jobs API throttle rates
        'job_start': '10/hour',  # Expensive operation
        'job_stop': '20/hour',  # Reasonable control
        'job_status': '120/minute',  # Allow frequent polling
        'job_logs': '30/minute',  # Log fetching is expensive
        'job_search': '60/minute',  # Match existing MCP rate
        'job_create': '20/hour',  # Prevent spam creation
        'job_bulk': '5/hour',  # Very restrictive for bulk ops
    },

    # Pagination
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 100,

    # Renderers
    'DEFAULT_RENDERER_CLASSES': [
        'rest_framework.renderers.JSONRenderer',
    ],

    # Parser classes
    'DEFAULT_PARSER_CLASSES': [
        'rest_framework.parsers.JSONParser',
    ],

    # Exception handling
    'EXCEPTION_HANDLER': 'rest_framework.views.exception_handler',

    # Schema generation (using drf-spectacular for OpenAPI 3.0)
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
}

# OpenAPI Documentation (drf-spectacular)
SPECTACULAR_SETTINGS = {
    'TITLE': 'CodePathFinder API',
    'DESCRIPTION': '''
REST API for managing code indexing jobs in CodePathFinder.

## Overview
This API provides comprehensive management of code indexing jobs, designed for
autonomous AI agent usage with excellent error messaging and documentation.

## Authentication
All endpoints require a Project API Key passed as a Bearer token:
```
Authorization: Bearer cpf_<prefix>_<secret>
```

API keys can be created from the project dashboard or via the API itself.

## Rate Limits
- Job start: 10/hour (expensive operation)
- Job stop: 20/hour
- Status checks: 120/minute (frequent polling allowed)
- Log fetching: 30/minute
- Search: 60/minute

## Status Flow
```
pending -> running -> completed
               |-> failed
               |-> watching (if watch_mode)
               |-> stopped (manual)
```

## Error Responses
All errors include:
- `code`: Machine-readable error code
- `message`: Human-readable description
- `remediation`: Steps to fix the error
''',
    'VERSION': '1.0.0',
    'SERVE_INCLUDE_SCHEMA': False,
    'COMPONENT_SPLIT_REQUEST': True,
    'TAGS': [
        {'name': 'Projects', 'description': 'Project CRUD operations'},
        {'name': 'Jobs', 'description': 'Job lifecycle management (start, stop, status)'},
        {'name': 'Search', 'description': 'Search indexed code'},
        {'name': 'Bulk Operations', 'description': 'Batch operations on multiple projects'},
    ],
    # Register custom authentication extensions
    'EXTENSIONS': [
        'api.jobs.openapi_auth.ProjectAPIKeyAuthExtension',
        'api.jobs.openapi_auth.MCPAPIKeyAuthExtension',
        'api.jobs.openapi_auth.ChatAPIKeyAuthExtension',
    ],
}

# LibreChat Integration
# URL for embedding LibreChat in an iframe (external/browser-accessible URL)
# Uses HTTPS on port 3443 served by nginx to match CodePathfinder's HTTPS
LIBRECHAT_EXTERNAL_URL = os.getenv('LIBRECHAT_EXTERNAL_URL', 'https://localhost:3443')
