# Generated by Django 4.2.26 on 2026-01-09 05:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Unique skill identifier (e.g., 'code-review', 'test-generator')", max_length=255, unique=True)),
                ('description', models.TextField(help_text='Brief description of what the skill does (used for semantic search)')),
                ('instructions', models.TextField(help_text='Full instructions/prompt for the AI agent')),
                ('allowed_tools', models.JSONField(blank=True, default=list, help_text='List of tool names the skill is allowed to use')),
                ('tags', models.JSONField(blank=True, default=list, help_text='Tags for categorization and filtering')),
                ('context_files', models.JSONField(blank=True, default=dict, help_text='Dict of file paths to content for additional context')),
                ('is_curated', models.BooleanField(default=False, help_text='Whether this skill is curated/verified by administrators')),
                ('usage_count', models.IntegerField(default=0, help_text='Number of times this skill has been used')),
                ('github_path', models.CharField(blank=True, help_text="Path in the skills repository (e.g., 'skills/code-review/SKILL.md')", max_length=500)),
                ('last_synced', models.DateTimeField(blank=True, help_text='Last time this skill was synced from GitHub', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this skill is available for use')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this skill (null if synced from GitHub)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_skills', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Skill',
                'verbose_name_plural': 'Skills',
                'ordering': ['-is_curated', '-usage_count', 'name'],
            },
        ),
    ]
