# Generated by Django 4.2.26 on 2026-01-11 05:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('skills', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SkillUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('used_at', models.DateTimeField(auto_now=True, help_text='Last time this skill was used by this user')),
                ('usage_count', models.IntegerField(default=1, help_text='Number of times this user has used this skill')),
                ('skill', models.ForeignKey(help_text='Skill that was used', on_delete=django.db.models.deletion.CASCADE, related_name='user_usages', to='skills.skill')),
                ('user', models.ForeignKey(help_text='User who used the skill', on_delete=django.db.models.deletion.CASCADE, related_name='skill_usages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Skill Usage',
                'verbose_name_plural': 'Skill Usages',
                'ordering': ['-used_at'],
                'indexes': [models.Index(fields=['user', '-used_at'], name='skills_skil_user_id_522f78_idx'), models.Index(fields=['user', '-usage_count'], name='skills_skil_user_id_a4e5b2_idx')],
                'unique_together': {('user', 'skill')},
            },
        ),
    ]
