# Generated by Django 4.2.27 on 2026-01-11 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0003_default_skills'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='is_hidden',
            field=models.BooleanField(default=False, help_text='Whether this skill is hidden from UI/API (exists in GitHub but not visible)'),
        ),
    ]
