# Generated by Django 4.2.26 on 2026-01-12 04:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('skills', '0004_add_is_hidden_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='deleted_at',
            field=models.DateTimeField(blank=True, help_text='When this skill was soft-deleted (hidden by admin). Set to re-enable restoration.', null=True),
        ),
        migrations.AddField(
            model_name='skill',
            name='deleted_by',
            field=models.ForeignKey(blank=True, help_text='User who deleted (hid) this skill', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_skills', to=settings.AUTH_USER_MODEL),
        ),
    ]
