# Generated by Django 4.2.26 on 2025-11-29 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pathfinderproject',
            name='branch',
            field=models.CharField(blank=True, help_text='Specific branch to index (default: auto-detect)', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='pathfinderproject',
            name='clean_index',
            field=models.BooleanField(default=False, help_text='Delete existing index before starting (full rebuild)'),
        ),
        migrations.AddField(
            model_name='pathfinderproject',
            name='concurrency',
            field=models.IntegerField(default=4, help_text='Number of parallel workers (recommended: CPU core count)'),
        ),
        migrations.AddField(
            model_name='pathfinderproject',
            name='custom_index_name',
            field=models.CharField(blank=True, help_text='Custom Elasticsearch index name (default: auto-generated)', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='pathfinderproject',
            name='github_token',
            field=models.CharField(blank=True, help_text='GitHub Personal Access Token for private repositories', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='pathfinderproject',
            name='pull_before_index',
            field=models.BooleanField(default=False, help_text='Git pull before indexing (for incremental updates)'),
        ),
        migrations.AddField(
            model_name='pathfinderproject',
            name='watch_mode',
            field=models.BooleanField(default=False, help_text='Keep indexer running for continuous updates'),
        ),
    ]
