# Generated by Django 4.2.27 on 2025-12-06 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_pathfinderproject_branch_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pathfinderproject',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='pathfinderproject',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('enabled', 'Enabled'), ('disabled', 'Disabled')], default='pending', max_length=20),
        ),
    ]
