# Generated by Django 4.2.27 on 2025-12-08 15:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0003_pathfinderproject_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pathfinderproject',
            name='shared_with',
            field=models.ManyToManyField(blank=True, help_text='Users who can view this project', related_name='shared_projects', to=settings.AUTH_USER_MODEL),
        ),
    ]
