# Generated by Django 4.2.27 on 2025-12-09 21:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_pathfinderproject_shared_with'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectAPIKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prefix', models.CharField(help_text="Key prefix for display (e.g., 'cpf_abc')", max_length=8)),
                ('hashed_key', models.CharField(help_text='SHA256 hash of the full API key', max_length=128)),
                ('label', models.CharField(default='CLI Key', help_text="User-friendly label (e.g., 'My Laptop')", max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_used_at', models.DateTimeField(blank=True, help_text='Last time this key was used', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Inactive keys are rejected')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_keys', to='projects.pathfinderproject')),
            ],
            options={
                'verbose_name': 'Project API Key',
                'verbose_name_plural': 'Project API Keys',
                'ordering': ['-created_at'],
            },
        ),
    ]
