# Generated by Django 4.2.27 on 2025-12-11 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_projectapikey'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pathfinderproject',
            name='custom_index_name',
            field=models.CharField(blank=True, default='', help_text='Custom Elasticsearch index name (default: auto-generated as project-{id})', max_length=255),
        ),
        migrations.AlterField(
            model_name='pathfinderproject',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('stopped', 'Stopped'), ('enabled', 'Enabled'), ('disabled', 'Disabled')], default='pending', max_length=20),
        ),
    ]
