# Generated by Django 4.2.26 on 2025-12-18 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_auto_generate_custom_index_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectapikey',
            name='scope',
            field=models.CharField(choices=[('mcp', 'MCP Tools Only'), ('chat', 'Chat Only'), ('all', 'All Access')], default='mcp', help_text='Access scope for this key', max_length=10),
        ),
        migrations.AlterField(
            model_name='pathfinderproject',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('watching', 'Watching'), ('stopped', 'Stopped'), ('enabled', 'Enabled'), ('disabled', 'Disabled')], default='pending', max_length=20),
        ),
    ]
