# Generated by Django 4.2.26 on 2025-12-18 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_projectapikey_scope_alter_pathfinderproject_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='pathfinderproject',
            name='is_enabled',
            field=models.BooleanField(default=True, help_text='Manual toggle to enable/disable project search and access'),
        ),
        migrations.AlterField(
            model_name='pathfinderproject',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('watching', 'Watching'), ('stopped', 'Stopped')], default='pending', max_length=20),
        ),
    ]
