# Generated by Django 4.2.28 on 2026-02-10 14:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_pathfinderproject_is_enabled_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_id', models.CharField(help_text='Kubernetes job name or Docker container ID', max_length=100)),
                ('started_at', models.DateTimeField(help_text='When the job was started')),
                ('completed_at', models.DateTimeField(blank=True, help_text='When the job completed (null if still running)', null=True)),
                ('final_status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('watching', 'Watching'), ('stopped', 'Stopped')], default='running', help_text='Final status of the job run', max_length=20)),
                ('options', models.JSONField(default=dict, help_text='Job options used (clean_index, branch, concurrency, etc.)')),
                ('result', models.JSONField(default=dict, help_text='Job results (files_indexed, documents_created, errors, etc.)')),
                ('error_message', models.TextField(blank=True, default='', help_text='Error message if job failed')),
                ('triggered_by', models.CharField(default='web', help_text='How the job was triggered (web, api, schedule)', max_length=50)),
                ('project', models.ForeignKey(help_text='The project this job run belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='job_runs', to='projects.pathfinderproject')),
            ],
            options={
                'verbose_name': 'Job Run',
                'verbose_name_plural': 'Job Runs',
                'ordering': ['-started_at'],
                'indexes': [models.Index(fields=['project', '-started_at'], name='projects_jo_project_072631_idx'), models.Index(fields=['final_status'], name='projects_jo_final_s_a80cbd_idx')],
            },
        ),
    ]
