# Generated by Django 4.2.26 on 2026-01-09 05:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('elasticsearch_endpoint', models.URLField(blank=True, help_text='Self-hosted Elasticsearch URL')),
                ('elasticsearch_cloud_id', models.CharField(blank=True, help_text='Elastic Cloud ID (alternative to endpoint)', max_length=255)),
                ('elasticsearch_user', models.CharField(blank=True, max_length=255)),
                ('elasticsearch_password', models.CharField(blank=True, max_length=255)),
                ('elasticsearch_api_key', models.CharField(blank=True, max_length=255)),
                ('elasticsearch_index', models.CharField(default='code-chunks', help_text='Default index name for code chunks', max_length=255)),
                ('elasticsearch_inference_id', models.CharField(default='.elser-2-elasticsearch', help_text='Inference endpoint for semantic search', max_length=255)),
                ('skills_repo_url', models.URLField(blank=True, help_text='GitHub repo containing skills (e.g., https://github.com/org/skills)')),
                ('skills_repo_token', models.CharField(blank=True, help_text='Personal Access Token for private repos', max_length=255)),
                ('skills_repo_branch', models.CharField(default='main', help_text='Branch to sync skills from', max_length=255)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='system_settings_updates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'System Settings',
                'verbose_name_plural': 'System Settings',
            },
        ),
    ]
