# Generated by Django 4.2.26 on 2026-01-09 05:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_systemsettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserGitHubSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('github_username', models.CharField(blank=True, max_length=255)),
                ('github_token', models.CharField(blank=True, help_text='Personal Access Token for GitHub API operations', max_length=255)),
                ('last_validated_at', models.DateTimeField(blank=True, help_text='Last time the token was validated against GitHub API', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='github_settings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User GitHub Settings',
                'verbose_name_plural': 'User GitHub Settings',
            },
        ),
    ]
