# Generated by Django 4.2.26 on 2026-01-11 16:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_pathfinderproject_is_enabled_and_more'),
        ('core', '0004_populate_default_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='favorite_chat_project',
            field=models.ForeignKey(blank=True, help_text='Default project for chat interface', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='favorited_by_users', to='projects.pathfinderproject'),
        ),
    ]
