# Generated by Django 4.2.26 on 2026-01-14 04:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_add_favorite_chat_project'),
    ]

    operations = [
        migrations.CreateModel(
            name='LLMProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('provider', models.CharField(choices=[('openai', 'OpenAI'), ('anthropic', 'Anthropic'), ('bedrock', 'AWS Bedrock'), ('vertex_ai', 'Google Vertex AI'), ('azure', 'Azure OpenAI'), ('groq', 'Groq'), ('together_ai', 'Together AI'), ('zhipu', 'Zhipu AI'), ('ollama', 'Ollama (Local)'), ('openrouter', 'OpenRouter')], max_length=50)),
                ('api_key', models.CharField(blank=True, help_text='API key for this provider (leave empty to use environment variable)', max_length=500)),
                ('api_base', models.URLField(blank=True, help_text='Custom API base URL (optional, for self-hosted or proxy endpoints)')),
                ('is_active', models.BooleanField(default=True)),
                ('is_default', models.BooleanField(default=False, help_text='Use this provider by default when no model is specified')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'LLM Provider',
                'verbose_name_plural': 'LLM Providers',
                'ordering': ['-is_default', 'name'],
            },
        ),
        migrations.CreateModel(
            name='LLMModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_id', models.CharField(help_text='Model identifier (e.g., gpt-4o, claude-3-5-sonnet-20241022)', max_length=100)),
                ('display_name', models.CharField(help_text='Human-readable name shown in UI', max_length=100)),
                ('is_default', models.BooleanField(default=False, help_text='Default model for this provider')),
                ('max_tokens', models.IntegerField(default=4096, help_text='Maximum output tokens')),
                ('context_window', models.IntegerField(default=128000, help_text='Context window size in tokens')),
                ('supports_tools', models.BooleanField(default=True, help_text='Whether this model supports function/tool calling')),
                ('supports_vision', models.BooleanField(default=False, help_text='Whether this model supports image inputs')),
                ('cost_per_1k_input', models.DecimalField(blank=True, decimal_places=6, help_text='Cost per 1K input tokens (USD)', max_digits=10, null=True)),
                ('cost_per_1k_output', models.DecimalField(blank=True, decimal_places=6, help_text='Cost per 1K output tokens (USD)', max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='models', to='core.llmprovider')),
            ],
            options={
                'verbose_name': 'LLM Model',
                'verbose_name_plural': 'LLM Models',
                'ordering': ['provider', '-is_default', 'display_name'],
                'unique_together': {('provider', 'model_id')},
            },
        ),
    ]
