# Generated by Claude - Data migration to populate default LLM providers

from django.db import migrations


def populate_llm_providers(apps, schema_editor):
    """
    Populate default LLM providers and models.

    API keys are left empty - they should be set via:
    1. Django Admin UI
    2. Environment variables (ANTHROPIC_API_KEY, OPENAI_API_KEY, etc.)
    """
    LLMProvider = apps.get_model('core', 'LLMProvider')
    LLMModel = apps.get_model('core', 'LLMModel')

    providers_data = [
        # Anthropic (Default)
        {
            'name': 'Anthropic',
            'provider': 'anthropic',
            'is_default': True,
            'is_active': True,
            'models': [
                {
                    'model_id': 'claude-sonnet-4-20250514',
                    'display_name': 'Claude Sonnet 4',
                    'is_default': True,
                    'max_tokens': 8192,
                    'context_window': 200000,
                    'supports_tools': True,
                    'supports_vision': True,
                    'cost_per_1k_input': 0.003,
                    'cost_per_1k_output': 0.015,
                },
                {
                    'model_id': 'claude-opus-4-20250514',
                    'display_name': 'Claude Opus 4',
                    'is_default': False,
                    'max_tokens': 8192,
                    'context_window': 200000,
                    'supports_tools': True,
                    'supports_vision': True,
                    'cost_per_1k_input': 0.015,
                    'cost_per_1k_output': 0.075,
                },
                {
                    'model_id': 'claude-3-5-haiku-20241022',
                    'display_name': 'Claude 3.5 Haiku',
                    'is_default': False,
                    'max_tokens': 8192,
                    'context_window': 200000,
                    'supports_tools': True,
                    'supports_vision': True,
                    'cost_per_1k_input': 0.0008,
                    'cost_per_1k_output': 0.004,
                },
            ]
        },
        # OpenAI
        {
            'name': 'OpenAI',
            'provider': 'openai',
            'is_default': False,
            'is_active': True,
            'models': [
                {
                    'model_id': 'gpt-5.2',
                    'display_name': 'GPT-5.2',
                    'is_default': True,
                    'max_tokens': 16384,
                    'context_window': 256000,
                    'supports_tools': True,
                    'supports_vision': True,
                    'cost_per_1k_input': 0.005,
                    'cost_per_1k_output': 0.02,
                },
                {
                    'model_id': 'gpt-5.2-pro',
                    'display_name': 'GPT-5.2 Pro',
                    'is_default': False,
                    'max_tokens': 32768,
                    'context_window': 512000,
                    'supports_tools': True,
                    'supports_vision': True,
                    'cost_per_1k_input': 0.01,
                    'cost_per_1k_output': 0.04,
                },
                {
                    'model_id': 'gpt-5-mini',
                    'display_name': 'GPT-5 Mini',
                    'is_default': False,
                    'max_tokens': 8192,
                    'context_window': 128000,
                    'supports_tools': True,
                    'supports_vision': True,
                    'cost_per_1k_input': 0.001,
                    'cost_per_1k_output': 0.004,
                },
                {
                    'model_id': 'gpt-5-nano',
                    'display_name': 'GPT-5 Nano',
                    'is_default': False,
                    'max_tokens': 4096,
                    'context_window': 64000,
                    'supports_tools': True,
                    'supports_vision': True,
                    'cost_per_1k_input': 0.0002,
                    'cost_per_1k_output': 0.0008,
                },
                {
                    'model_id': 'o1',
                    'display_name': 'o1 (Reasoning)',
                    'is_default': False,
                    'max_tokens': 32768,
                    'context_window': 200000,
                    'supports_tools': True,
                    'supports_vision': True,
                    'cost_per_1k_input': 0.015,
                    'cost_per_1k_output': 0.06,
                },
                {
                    'model_id': 'o3-mini',
                    'display_name': 'o3-mini (Reasoning)',
                    'is_default': False,
                    'max_tokens': 65536,
                    'context_window': 200000,
                    'supports_tools': True,
                    'supports_vision': False,
                    'cost_per_1k_input': 0.00115,
                    'cost_per_1k_output': 0.0044,
                },
            ]
        },
        # Google Vertex AI
        {
            'name': 'Google Vertex AI',
            'provider': 'vertex_ai',
            'is_default': False,
            'is_active': True,
            'models': [
                {
                    'model_id': 'gemini-2.0-flash',
                    'display_name': 'Gemini 2.0 Flash',
                    'is_default': True,
                    'max_tokens': 8192,
                    'context_window': 1000000,
                    'supports_tools': True,
                    'supports_vision': True,
                    'cost_per_1k_input': 0.00010,
                    'cost_per_1k_output': 0.00040,
                },
                {
                    'model_id': 'gemini-2.0-flash-thinking-exp',
                    'display_name': 'Gemini 2.0 Flash Thinking',
                    'is_default': False,
                    'max_tokens': 8192,
                    'context_window': 1000000,
                    'supports_tools': True,
                    'supports_vision': True,
                    'cost_per_1k_input': 0.00010,
                    'cost_per_1k_output': 0.00040,
                },
                {
                    'model_id': 'gemini-1.5-pro',
                    'display_name': 'Gemini 1.5 Pro',
                    'is_default': False,
                    'max_tokens': 8192,
                    'context_window': 2000000,
                    'supports_tools': True,
                    'supports_vision': True,
                    'cost_per_1k_input': 0.00125,
                    'cost_per_1k_output': 0.005,
                },
            ]
        },
        # Zhipu AI (Z.AI / GLM)
        {
            'name': 'Zhipu AI',
            'provider': 'zhipu',
            'is_default': False,
            'is_active': True,
            'models': [
                {
                    'model_id': 'glm-4-plus',
                    'display_name': 'GLM-4 Plus',
                    'is_default': True,
                    'max_tokens': 4096,
                    'context_window': 128000,
                    'supports_tools': True,
                    'supports_vision': False,
                    'cost_per_1k_input': 0.0007,
                    'cost_per_1k_output': 0.0007,
                },
                {
                    'model_id': 'glm-4v-plus',
                    'display_name': 'GLM-4V Plus (Vision)',
                    'is_default': False,
                    'max_tokens': 4096,
                    'context_window': 8192,
                    'supports_tools': True,
                    'supports_vision': True,
                    'cost_per_1k_input': 0.0014,
                    'cost_per_1k_output': 0.0014,
                },
                {
                    'model_id': 'glm-4-flash',
                    'display_name': 'GLM-4 Flash',
                    'is_default': False,
                    'max_tokens': 4096,
                    'context_window': 128000,
                    'supports_tools': True,
                    'supports_vision': False,
                    'cost_per_1k_input': 0.00007,
                    'cost_per_1k_output': 0.00007,
                },
            ]
        },
        # AWS Bedrock
        {
            'name': 'AWS Bedrock',
            'provider': 'bedrock',
            'is_default': False,
            'is_active': True,
            'models': [
                {
                    'model_id': 'anthropic.claude-3-5-sonnet-20241022-v2:0',
                    'display_name': 'Claude 3.5 Sonnet (Bedrock)',
                    'is_default': True,
                    'max_tokens': 8192,
                    'context_window': 200000,
                    'supports_tools': True,
                    'supports_vision': True,
                    'cost_per_1k_input': 0.003,
                    'cost_per_1k_output': 0.015,
                },
                {
                    'model_id': 'anthropic.claude-3-haiku-20240307-v1:0',
                    'display_name': 'Claude 3 Haiku (Bedrock)',
                    'is_default': False,
                    'max_tokens': 4096,
                    'context_window': 200000,
                    'supports_tools': True,
                    'supports_vision': True,
                    'cost_per_1k_input': 0.00025,
                    'cost_per_1k_output': 0.00125,
                },
                {
                    'model_id': 'amazon.nova-pro-v1:0',
                    'display_name': 'Amazon Nova Pro',
                    'is_default': False,
                    'max_tokens': 5000,
                    'context_window': 300000,
                    'supports_tools': True,
                    'supports_vision': True,
                    'cost_per_1k_input': 0.0008,
                    'cost_per_1k_output': 0.0032,
                },
                {
                    'model_id': 'amazon.nova-lite-v1:0',
                    'display_name': 'Amazon Nova Lite',
                    'is_default': False,
                    'max_tokens': 5000,
                    'context_window': 300000,
                    'supports_tools': True,
                    'supports_vision': True,
                    'cost_per_1k_input': 0.00006,
                    'cost_per_1k_output': 0.00024,
                },
                {
                    'model_id': 'meta.llama3-70b-instruct-v1:0',
                    'display_name': 'Llama 3 70B (Bedrock)',
                    'is_default': False,
                    'max_tokens': 2048,
                    'context_window': 8192,
                    'supports_tools': True,
                    'supports_vision': False,
                    'cost_per_1k_input': 0.00265,
                    'cost_per_1k_output': 0.0035,
                },
            ]
        },
        # Snowflake Cortex (via OpenAI-compatible API)
        {
            'name': 'Snowflake Cortex',
            'provider': 'openai',  # Uses OpenAI-compatible API
            'api_base': '',  # User must set their Snowflake endpoint
            'is_default': False,
            'is_active': False,  # Disabled by default - requires Snowflake setup
            'models': [
                {
                    'model_id': 'llama3.1-70b',
                    'display_name': 'Llama 3.1 70B (Cortex)',
                    'is_default': True,
                    'max_tokens': 4096,
                    'context_window': 128000,
                    'supports_tools': True,
                    'supports_vision': False,
                    'cost_per_1k_input': None,  # Varies by Snowflake account
                    'cost_per_1k_output': None,
                },
                {
                    'model_id': 'llama3.1-405b',
                    'display_name': 'Llama 3.1 405B (Cortex)',
                    'is_default': False,
                    'max_tokens': 4096,
                    'context_window': 128000,
                    'supports_tools': True,
                    'supports_vision': False,
                    'cost_per_1k_input': None,
                    'cost_per_1k_output': None,
                },
                {
                    'model_id': 'mistral-large2',
                    'display_name': 'Mistral Large 2 (Cortex)',
                    'is_default': False,
                    'max_tokens': 4096,
                    'context_window': 128000,
                    'supports_tools': True,
                    'supports_vision': False,
                    'cost_per_1k_input': None,
                    'cost_per_1k_output': None,
                },
            ]
        },
        # Groq (Fast inference)
        {
            'name': 'Groq',
            'provider': 'groq',
            'is_default': False,
            'is_active': True,
            'models': [
                {
                    'model_id': 'llama-3.3-70b-versatile',
                    'display_name': 'Llama 3.3 70B',
                    'is_default': True,
                    'max_tokens': 8192,
                    'context_window': 128000,
                    'supports_tools': True,
                    'supports_vision': False,
                    'cost_per_1k_input': 0.00059,
                    'cost_per_1k_output': 0.00079,
                },
                {
                    'model_id': 'mixtral-8x7b-32768',
                    'display_name': 'Mixtral 8x7B',
                    'is_default': False,
                    'max_tokens': 4096,
                    'context_window': 32768,
                    'supports_tools': True,
                    'supports_vision': False,
                    'cost_per_1k_input': 0.00024,
                    'cost_per_1k_output': 0.00024,
                },
            ]
        },
        # OpenRouter (Multi-provider gateway)
        {
            'name': 'OpenRouter',
            'provider': 'openrouter',
            'is_default': False,
            'is_active': True,
            'models': [
                {
                    'model_id': 'anthropic/claude-sonnet-4',
                    'display_name': 'Claude Sonnet 4 (OpenRouter)',
                    'is_default': True,
                    'max_tokens': 8192,
                    'context_window': 200000,
                    'supports_tools': True,
                    'supports_vision': True,
                    'cost_per_1k_input': 0.003,
                    'cost_per_1k_output': 0.015,
                },
                {
                    'model_id': 'openai/gpt-5.2',
                    'display_name': 'GPT-5.2 (OpenRouter)',
                    'is_default': False,
                    'max_tokens': 16384,
                    'context_window': 256000,
                    'supports_tools': True,
                    'supports_vision': True,
                    'cost_per_1k_input': 0.005,
                    'cost_per_1k_output': 0.02,
                },
                {
                    'model_id': 'google/gemini-2.0-flash-001',
                    'display_name': 'Gemini 2.0 Flash (OpenRouter)',
                    'is_default': False,
                    'max_tokens': 8192,
                    'context_window': 1000000,
                    'supports_tools': True,
                    'supports_vision': True,
                    'cost_per_1k_input': 0.0001,
                    'cost_per_1k_output': 0.0004,
                },
                {
                    'model_id': 'deepseek/deepseek-chat',
                    'display_name': 'DeepSeek V3 (OpenRouter)',
                    'is_default': False,
                    'max_tokens': 8192,
                    'context_window': 64000,
                    'supports_tools': True,
                    'supports_vision': False,
                    'cost_per_1k_input': 0.00014,
                    'cost_per_1k_output': 0.00028,
                },
            ]
        },
    ]

    for provider_data in providers_data:
        models_data = provider_data.pop('models')
        api_base = provider_data.pop('api_base', '')

        provider = LLMProvider.objects.create(
            api_base=api_base,
            **provider_data
        )

        for model_data in models_data:
            LLMModel.objects.create(
                provider=provider,
                **model_data
            )


def remove_llm_providers(apps, schema_editor):
    """Remove all LLM providers (reverse migration)."""
    LLMProvider = apps.get_model('core', 'LLMProvider')
    LLMProvider.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_add_llm_provider_models'),
    ]

    operations = [
        migrations.RunPython(populate_llm_providers, remove_llm_providers),
    ]
