# Generated by Claude - Data migration to update OpenAI models to GPT-5 series

from django.db import migrations


def update_openai_models(apps, schema_editor):
    """
    Update OpenAI models from GPT-4o series to GPT-5 series.
    Also updates OpenRouter's GPT-4o to GPT-5.2.
    """
    LLMProvider = apps.get_model('core', 'LLMProvider')
    LLMModel = apps.get_model('core', 'LLMModel')

    # Update OpenAI provider models
    try:
        openai_provider = LLMProvider.objects.get(provider='openai', name='OpenAI')

        # Delete old GPT-4o models
        LLMModel.objects.filter(
            provider=openai_provider,
            model_id__in=['gpt-4o', 'gpt-4o-mini']
        ).delete()

        # Add new GPT-5 models
        new_models = [
            {
                'model_id': 'gpt-5.2',
                'display_name': 'GPT-5.2',
                'is_default': True,
                'max_tokens': 16384,
                'context_window': 256000,
                'supports_tools': True,
                'supports_vision': True,
                'cost_per_1k_input': 0.005,
                'cost_per_1k_output': 0.02,
            },
            {
                'model_id': 'gpt-5.2-pro',
                'display_name': 'GPT-5.2 Pro',
                'is_default': False,
                'max_tokens': 32768,
                'context_window': 512000,
                'supports_tools': True,
                'supports_vision': True,
                'cost_per_1k_input': 0.01,
                'cost_per_1k_output': 0.04,
            },
            {
                'model_id': 'gpt-5-mini',
                'display_name': 'GPT-5 Mini',
                'is_default': False,
                'max_tokens': 8192,
                'context_window': 128000,
                'supports_tools': True,
                'supports_vision': True,
                'cost_per_1k_input': 0.001,
                'cost_per_1k_output': 0.004,
            },
            {
                'model_id': 'gpt-5-nano',
                'display_name': 'GPT-5 Nano',
                'is_default': False,
                'max_tokens': 4096,
                'context_window': 64000,
                'supports_tools': True,
                'supports_vision': True,
                'cost_per_1k_input': 0.0002,
                'cost_per_1k_output': 0.0008,
            },
        ]

        # Unset any existing default
        LLMModel.objects.filter(provider=openai_provider, is_default=True).update(is_default=False)

        for model_data in new_models:
            model_id = model_data.pop('model_id')
            LLMModel.objects.update_or_create(
                provider=openai_provider,
                model_id=model_id,
                defaults=model_data
            )

    except LLMProvider.DoesNotExist:
        pass  # OpenAI provider doesn't exist, skip

    # Update OpenRouter's GPT-4o to GPT-5.2
    try:
        openrouter_provider = LLMProvider.objects.get(provider='openrouter', name='OpenRouter')

        LLMModel.objects.filter(
            provider=openrouter_provider,
            model_id='openai/gpt-4o'
        ).update(
            model_id='openai/gpt-5.2',
            display_name='GPT-5.2 (OpenRouter)',
            max_tokens=16384,
            context_window=256000,
            cost_per_1k_input=0.005,
            cost_per_1k_output=0.02,
        )
    except LLMProvider.DoesNotExist:
        pass  # OpenRouter provider doesn't exist, skip


def revert_openai_models(apps, schema_editor):
    """
    Revert GPT-5 models back to GPT-4o series.
    """
    LLMProvider = apps.get_model('core', 'LLMProvider')
    LLMModel = apps.get_model('core', 'LLMModel')

    # Revert OpenAI provider models
    try:
        openai_provider = LLMProvider.objects.get(provider='openai', name='OpenAI')

        # Delete GPT-5 models
        LLMModel.objects.filter(
            provider=openai_provider,
            model_id__in=['gpt-5.2', 'gpt-5.2-pro', 'gpt-5-mini', 'gpt-5-nano']
        ).delete()

        # Restore old GPT-4o models
        old_models = [
            {
                'model_id': 'gpt-4o',
                'display_name': 'GPT-4o',
                'is_default': True,
                'max_tokens': 4096,
                'context_window': 128000,
                'supports_tools': True,
                'supports_vision': True,
                'cost_per_1k_input': 0.0025,
                'cost_per_1k_output': 0.01,
            },
            {
                'model_id': 'gpt-4o-mini',
                'display_name': 'GPT-4o Mini',
                'is_default': False,
                'max_tokens': 4096,
                'context_window': 128000,
                'supports_tools': True,
                'supports_vision': True,
                'cost_per_1k_input': 0.00015,
                'cost_per_1k_output': 0.0006,
            },
        ]

        # Unset any existing default
        LLMModel.objects.filter(provider=openai_provider, is_default=True).update(is_default=False)

        for model_data in old_models:
            model_id = model_data.pop('model_id')
            LLMModel.objects.update_or_create(
                provider=openai_provider,
                model_id=model_id,
                defaults=model_data
            )

    except LLMProvider.DoesNotExist:
        pass

    # Revert OpenRouter's GPT-5.2 to GPT-4o
    try:
        openrouter_provider = LLMProvider.objects.get(provider='openrouter', name='OpenRouter')

        LLMModel.objects.filter(
            provider=openrouter_provider,
            model_id='openai/gpt-5.2'
        ).update(
            model_id='openai/gpt-4o',
            display_name='GPT-4o (OpenRouter)',
            max_tokens=4096,
            context_window=128000,
            cost_per_1k_input=0.0025,
            cost_per_1k_output=0.01,
        )
    except LLMProvider.DoesNotExist:
        pass


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_add_provider_specific_fields'),
    ]

    operations = [
        migrations.RunPython(update_openai_models, revert_openai_models),
    ]
