# Generated by Django 4.2.26 on 2026-01-17 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_update_openai_to_gpt5'),
    ]

    operations = [
        migrations.AddField(
            model_name='llmprovider',
            name='is_system',
            field=models.BooleanField(default=False, help_text='Standard provider managed by the system'),
        ),
        migrations.AddField(
            model_name='llmprovider',
            name='kibana_agent_id',
            field=models.CharField(blank=True, help_text='Kibana Agent Builder agent ID', max_length=100),
        ),
        migrations.AddField(
            model_name='llmprovider',
            name='kibana_endpoint',
            field=models.URLField(blank=True, help_text='Kibana endpoint URL (auto-derived from Elasticsearch by default)'),
        ),
        migrations.AlterField(
            model_name='llmprovider',
            name='provider',
            field=models.CharField(choices=[('openai', 'OpenAI'), ('anthropic', 'Anthropic'), ('bedrock', 'AWS Bedrock'), ('vertex_ai', 'Google Vertex AI'), ('azure', 'Azure OpenAI'), ('groq', 'Groq'), ('together_ai', 'Together AI'), ('zhipu', 'Zhipu AI'), ('ollama', 'Ollama (Local)'), ('openrouter', 'OpenRouter'), ('kibana', 'Kibana Agent Builder')], max_length=50),
        ),
    ]
