# Generated by Django 4.2.27 on 2026-01-23 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_llmprovider_is_system_llmprovider_kibana_agent_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='indexer_concurrency',
            field=models.IntegerField(default=8, help_text='Default number of parallel indexing workers (8 recommended for ELSER)'),
        ),
    ]
