# Generated by Django - Remove LLMProvider and LLMModel tables
# LLM configuration is now managed through LibreChat settings

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_add_llmprovider_health_stats'),
    ]

    operations = [
        # Drop LLMModel first since it has a foreign key to LLMProvider
        migrations.DeleteModel(
            name='LLMModel',
        ),
        migrations.DeleteModel(
            name='LLMProvider',
        ),
    ]
