# Generated by Django 4.2.29 on 2026-03-19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_otel_collector_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='setup_wizard_completed_at',
            field=models.DateTimeField(
                blank=True,
                help_text='When the admin completed (or dismissed) the setup wizard',
                null=True,
            ),
        ),
    ]
