apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: index-data-pvc
  namespace: codepathfinder
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: standard-rwo
