apiVersion: v1
kind: ServiceAccount
metadata:
  name: codepathfinder-ksa
  namespace: codepathfinder
  annotations:
    iam.gke.io/gcp-service-account: codepathfinder-sa@<YOUR_GCP_PROJECT>.iam.gserviceaccount.com
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: codepathfinder-role
  namespace: code-pathfinder
rules:
- apiGroups: ["batch"]
  resources: ["jobs"]
  verbs: ["create", "get", "list", "watch", "delete"]
- apiGroups: [""]
  resources: ["pods", "pods/log"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: codepathfinder-rolebinding
  namespace: code-pathfinder
subjects:
- kind: ServiceAccount
  name: codepathfinder-ksa
  namespace: codepathfinder
roleRef:
  kind: Role
  name: codepathfinder-role
  apiGroup: rbac.authorization.k8s.io
